name: Build and push SNMP UPS Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push multi-arch Docker image

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from config.json
        id: version
        run: |
          VERSION=$(jq -r .version snmp-ups-sim/config.json)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./snmp-ups-sim
          file: ./snmp-ups-sim/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            rafal83/snmp-ups-sim:latest
            rafal83/snmp-ups-sim:${{ steps.version.outputs.VERSION }}

      - name: Build and push donetick
        uses: docker/build-push-action@v5
        with:
          context: ./donetick
          file: ./donetick/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            rafal83/donetick:latest
            rafal83/donetick:1.1.57