name: Build and push SNMP UPS Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build multi-arch Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./snmp-ups-sim
          file: ./snmp-ups-sim/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: rafal83/snmp-ups-sim:latest
